/*
 * User Slice (Redux Toolkit)
 *
 * This file defines the user slice of the Redux state, handling authentication actions like login and logout.
 */

import { createSlice } from "@reduxjs/toolkit";

// Initial state with no logged-in user
const initialState = {
  currentUser: null,
};

// Create a slice for the user state with actions for login and logout
export const userSlice = createSlice({
  name: "user",
  initialState,
  reducers: {
    // Action for successful login, setting the current user and token
    loginSuccess: (state, action) => {
      state.currentUser = action.payload.user;
      localStorage.setItem("fittrack-app-token", action.payload.token);
    },
    // Action for logout, clearing the current user and removing the token
    logout: (state) => {
      state.currentUser = null;
      localStorage.removeItem("fitttrack-app-token");
    },
  },
});

// Export the actions generated by the slice
export const { loginSuccess, logout } = userSlice.actions;

// Export the reducer to be used in the Redux store
export default userSlice.reducer;